### ISSUE TITLE
2.0 breaks backwards compatibility

### ISSUE THREAD

**Issue by dustyjewett** [pusher-community/pusher-js-test-stub#18]
Our builds are breaking because 2.0 breaks backwards compatibility, but no other releases are available.

**Comment by leggetter** [comment]
@dustyjewett - are you pulling directly from the master branch? What will fix things for you? A v1.0.0 pushed to bower? A tag in GitHub?

**Comment by leggetter** [comment]
Git:

```bash
git clone git@github.com:pusher-community/pusher-js-test-stub.git
cd pusher-js-test-stub
git checkout tags/v1.0.0 -b v1.0.0
```

Bower:

```bash
bower install pusher-test-stub#v1.0.0
```

**Comment by dustyjewett** [comment]
This is the commit that we had downloaded as of this morning:
9d8c856

**Comment by leggetter** [comment]
Yeah. Also instructions for getting the 1.0.0 code. I did add the bower.json file in case that was helpful.

You can see the tag for the 1.0.0 tag here https://github.com/pusher-community/pusher-js-test-stub/commits/v1.0.0

Do the steps in the previous comment I made help you fix your build or do you need something else? Please let me know.

**Comment by dustyjewett** [comment]
Just including the commit hash for the previous version was enough to fix our build.  The 1.0.0 tag would also likely fix it.
