### ISSUE TITLE
Getting Pusher.ready is not a function

### ISSUE THREAD

**Issue by gabrieljoelc** [pusher-community/pusher-js-test-stub#20]
I'm getting this in `pusher.js` when loaded with `pusher-test-stub.js`:
![image](https://cloud.githubusercontent.com/assets/147849/13836404/3913735e-ebbe-11e5-9625-d61ca6fb9668.png)

Here's the HTML source showing that `application.js` (containing `pusher.js`) is loaded before `pusher-test-stub.js`
![image](https://cloud.githubusercontent.com/assets/147849/13836415/56daf060-ebbe-11e5-91a2-eb23c5930bf0.png)

**Comment by jackfranklin** [comment]
Hey,

Is that `Pusher.ready()` code written by you? I can't see it in this library (although I'm not super familiar so might have missed it).

**Comment by leggetter** [comment]
It's a callback when deps are loaded. Could have been removed in newer
versions.

IIRC I may have missed this and it should be added to the stub.

**Comment by jackfranklin** [comment]
@leggetter thank you - @jpatel531 as someone more up to date with PusherJS can you confirm / suggest the right fix? Do we just need to fake Pusher.ready in this stub?

**Comment by gabrieljoelc** [comment]
- defined [here](https://github.com/pusher/pusher-js/blob/master/dist/pusher.js#L152-L157)
- invoked [here](https://github.com/pusher/pusher-js/blob/master/dist/pusher.js#L1177-L1179)
- `initialize` invoked in all of [this](https://github.com/pusher/pusher-js/blob/master/dist/pusher.js#L1182-L1200)

**Comment by gabrieljoelc** [comment]
Your commits dates latest commit times are after the pusher.js 3.0.0 release so I assumed this library had been against the pusher.js 3.0.0. Is that a valid assumption?
from [here](https://github.com/pusher-community/pusher-js-test-stub/commits/master):
![image](https://cloud.githubusercontent.com/assets/147849/13851476/9bf93064-ec1b-11e5-87bd-7acee00a5125.png)
from [here](https://github.com/pusher/pusher-js/releases):
![image](https://cloud.githubusercontent.com/assets/147849/13851499/b196fbd6-ec1b-11e5-9fcb-e36674817b46.png)

**Comment by jpatel531** [comment]
i think the stub could just have `ready` as an empty function

i.e. `PusherTestStub.ready = function(){}`

**Comment by leggetter** [comment]
Yep. That's the solution. I hacked that in for a presentation but then
didn't get about to fixing in the actual library:
https://github.com/leggetter/realtime-app-dev-tips/blob/gh-pages/examples/twitter-viewer/bower_components/pusher-test-stub/dist/pusher-test-stub.js#L77

**Comment by jackfranklin** [comment]
@leggetter no worries, I can fix the actual library, TY

**Comment by jackfranklin** [comment]
@gabrieljoelc if you bower install V2.0.1 does that fix the issue?

**Comment by gabrieljoelc** [comment]
@jackfranklin I'm not getting that error anymore! i haven't done a full against the mocks yet though.

**Comment by jackfranklin** [comment]
@gabrieljoelc great! Let us know how that goes but I'm going to presume that this is fixed as of 2.0.1 :)
